

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OlanthroxxEntities : DbContext
{
    public OlanthroxxEntities()
        : base("name=OlanthroxxEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<tblApplicationSetting> tblApplicationSettings { get; set; }

    public virtual DbSet<tblLog> tblLogs { get; set; }

    public virtual DbSet<tblMasCommonType> tblMasCommonTypes { get; set; }

    public virtual DbSet<tblUser> tblUsers { get; set; }

    public virtual DbSet<tblUserSessionDetail> tblUserSessionDetails { get; set; }

    public virtual DbSet<tblCategory> tblCategories { get; set; }

    public virtual DbSet<tblPayment> tblPayments { get; set; }

    public virtual DbSet<tblUserDetail> tblUserDetails { get; set; }

    public virtual DbSet<tblMasState> tblMasStates { get; set; }

    public virtual DbSet<tblForgotPasswordHistory> tblForgotPasswordHistories { get; set; }

    public virtual DbSet<tblExpense> tblExpenses { get; set; }

    public virtual DbSet<tblBudgetDetail> tblBudgetDetails { get; set; }

    public virtual DbSet<tblProduct> tblProducts { get; set; }

    public virtual DbSet<tblProductReview> tblProductReviews { get; set; }

    public virtual DbSet<tblMasCity> tblMasCities { get; set; }

    public virtual DbSet<tblAddress> tblAddresses { get; set; }

    public virtual DbSet<tblOrderDetail> tblOrderDetails { get; set; }

    public virtual DbSet<tblTheaterDetail> tblTheaterDetails { get; set; }

    public virtual DbSet<tblMovieDetail> tblMovieDetails { get; set; }

    public virtual DbSet<tblMovieBookingHistory> tblMovieBookingHistories { get; set; }

    public virtual DbSet<tblMovieScreenTimingConfig> tblMovieScreenTimingConfigs { get; set; }

    public virtual DbSet<tblScreenDetail> tblScreenDetails { get; set; }

    public virtual DbSet<tblTempCartDetail> tblTempCartDetails { get; set; }

}

}

