
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblAddress
{

    public int AddressID { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string UserID { get; set; }

    public int CityID { get; set; }

    public int StateID { get; set; }

    public int Pincode { get; set; }

    public string FullAddress { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Landmark { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

}

}
