
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblExpense
{

    public int ExpID { get; set; }

    public int BudgetID_FK { get; set; }

    public string ExpName { get; set; }

    public int Amount { get; set; }

    public string UserID { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

}

}
