
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblForgotPasswordHistory
{

    public int ID { get; set; }

    public string Username { get; set; }

    public int AttemptNo { get; set; }

    public int MaxNoOfAttempts { get; set; }

    public System.DateTime ExpiryTime { get; set; }

    public string Link { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public System.Guid Key { get; set; }

    public Nullable<System.DateTime> PasswordChangedDate { get; set; }

    public Nullable<bool> IsValid { get; set; }

}

}
