
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblLog
{

    public int LogID { get; set; }

    public string IdentificationNo { get; set; }

    public string Data { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

}

}
