
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblMasCity
{

    public int CityID { get; set; }

    public int StateID_FK { get; set; }

    public string City { get; set; }

    public bool IsActive { get; set; }

    public string CreatedDate { get; set; }



    public virtual tblMasState tblMasState { get; set; }

}

}
