//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasState
    {
        public int StateID { get; set; }
        public string State { get; set; }
        public int CountryID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
