
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblMasCommonType
{

    public int CommonID { get; set; }

    public Nullable<int> Code { get; set; }

    public string MasterType { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
