
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblMovieScreenTimingConfig
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblMovieScreenTimingConfig()
    {

        this.tblMovieBookingHistories = new HashSet<tblMovieBookingHistory>();

    }


    public int ScreenTimingConfigID { get; set; }

    public int MovieID_FK { get; set; }

    public int ScreenID_FK { get; set; }

    public int TimingID { get; set; }

    public bool IsActive { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<System.DateTime> MovieDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMovieBookingHistory> tblMovieBookingHistories { get; set; }

    public virtual tblMovieDetail tblMovieDetail { get; set; }

    public virtual tblScreenDetail tblScreenDetail { get; set; }

}

}
