
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblOrderDetail
{

    public int ID { get; set; }

    public System.Guid OrderID { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    public int Amount { get; set; }

    public string UserID { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<int> OrderStatus { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> ShippingAddressID_FK { get; set; }

    public Nullable<int> BillingAddressID_FK { get; set; }

    public Nullable<bool> OTPToBeShown { get; set; }

    public Nullable<int> OTP { get; set; }



    public virtual tblProduct tblProduct { get; set; }

}

}
