
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblPayment
{

    public int PaymentID { get; set; }

    public System.Guid OrderID { get; set; }

    public string UserName { get; set; }

    public int TotalPayableAmount { get; set; }

    public string PaymentMode { get; set; }

    public int PaymentStatus { get; set; }

    public string PaymentDetails { get; set; }

    public string TransactionNo { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string ChequeNo { get; set; }

    public Nullable<System.DateTime> ChequeDate { get; set; }

    public string AccountNo { get; set; }

    public string UPI_ID { get; set; }

    public string IFSC_Code { get; set; }

    public string PaymentOf { get; set; }

}

}
