
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblProduct
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblProduct()
    {

        this.tblProductReviews = new HashSet<tblProductReview>();

        this.tblOrderDetails = new HashSet<tblOrderDetail>();

    }


    public int ProductID { get; set; }

    public string PName { get; set; }

    public string PTitle { get; set; }

    public string PDescription { get; set; }

    public int CategoryID_FK { get; set; }

    public int Quantity { get; set; }

    public int Price { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public string SellerName { get; set; }

    public string ImgPath { get; set; }

    public Nullable<int> DiscountPer { get; set; }

    public Nullable<int> ItemsSold { get; set; }



    public virtual tblCategory tblCategory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblProductReview> tblProductReviews { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }

}

}
