
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblProductReview
{

    public int ReviewID { get; set; }

    public int ProductID_FK { get; set; }

    public System.Guid OrderID_FK { get; set; }

    public int Rating { get; set; }

    public string Review { get; set; }

    public string ImgPath { get; set; }

    public string UserID { get; set; }

    public System.DateTime CreatedDate { get; set; }



    public virtual tblProduct tblProduct { get; set; }

}

}
