
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblScreenDetail
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblScreenDetail()
    {

        this.tblMovieScreenTimingConfigs = new HashSet<tblMovieScreenTimingConfig>();

    }


    public int ScreenID { get; set; }

    public int ScreenNo { get; set; }

    public int TheaterID_FK { get; set; }

    public int NoOfSeatsSilver { get; set; }

    public int PriceSilver { get; set; }

    public int NoOfSeatsGold { get; set; }

    public int PriceGold { get; set; }

    public int NoOfSeatsPlatinum { get; set; }

    public int PricePlatinum { get; set; }

    public int NoOfSeatsRecliner { get; set; }

    public int PriceRecliner { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public bool IsActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMovieScreenTimingConfig> tblMovieScreenTimingConfigs { get; set; }

    public virtual tblTheaterDetail tblTheaterDetail { get; set; }

}

}
