
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblUserDetail
{

    public int UserDetailsID { get; set; }

    public int AccountID_FK { get; set; }

    public string FirstName { get; set; }

    public string MidName { get; set; }

    public string LastName { get; set; }

    public string MobileNo { get; set; }

    public string EmailID { get; set; }

    public string AadharNumber { get; set; }

    public string State { get; set; }

    public string City { get; set; }

    public int PinCode { get; set; }

    public string FullAddress { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public string UserImgPath { get; set; }



    public virtual tblUser tblUser { get; set; }

}

}
